title: Marc Philipp
owner: Marc Philipp

baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.marcphilipp.de" # the base hostname & protocol for your site
disqus_short_name: marcphilipp

email: mail@marcphilipp.de
twitter_username: marcphilipp
github_username:  marcphilipp

markdown: kramdown
highlighter: rouge
permalink: /blog/:year/:month/:day/:title/
excerpt_separator: "<!--more-->"

defaults:
  -
    scope:
      path: ""
    values:
      lang: en
  -
    scope:
      path: ""
      type: "posts"
    values:
      is_post: true
      layout: post
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: page

exclude: [ Gemfile, en/contact.html, en/portfolio.html ]

# Piwik
piwik_url: web864.we20e.netcup.net/piwik
piwik_siteid: 1
