title: Marc Philipp

baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.marcphilipp.de" # the base hostname & protocol for your site

email: mail@marcphilipp.de
twitter_username: marcphilipp
github_username:  marcphilipp

markdown: kramdown
permalink: /blog/:year/:month/:day/:title/