title: Marc Philipp
owner: Marc Philipp

baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.marcphilipp.de" # the base hostname & protocol for your site
disqus_short_name: marcphilipp

email: mail@marcphilipp.de
twitter_username: marcphilipp
github_username:  marcphilipp

markdown: kramdown
permalink: /blog/:year/:month/:day/:title/
excerpt_separator: "<!--more-->"

paginate: 8
paginate_path: "/blog/page:num/"

exclude: [ Gemfile, contact.html, portfolio.html ]

# Piwik
piwik_url: web864.we20e.netcup.net/piwik
piwik_siteid: 3
