title: Marc Philipp
owner: Marc Philipp

baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://www.marcphilipp.de" # the base hostname & protocol for your site
disqus_short_name: marcphilipp

friendly_captcha_sitekey: FCMNNLKPCHTQMILM
#contact_form_endpoint: http://127.0.0.1:8080/submit
contact_form_endpoint: https://contact.marcphilipp.de/submit

email: mail@marcphilipp.de
github_username:  marcphilipp

markdown: kramdown
highlighter: rouge
permalink: /blog/:year/:month/:day/:title/
excerpt_separator: "<!--more-->"

plugins:
  - jekyll-redirect-from

defaults:
  -
    scope:
      path: ""
    values:
      lang: en
  -
    scope:
      path: ""
      type: "posts"
    values:
      is_post: true
      layout: post
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: page

exclude: [ Gemfile, en/portfolio.html ]
